### ISSUE TITLE
Iris causing Message App Store to Look Like Photos

### ISSUE THREAD

**Issue by ianhandsup** [jacobcxdev/Iris#10]
![image](https://user-images.githubusercontent.com/48187239/84717734-ba82e980-af44-11ea-85d5-c8ce0e171a73.jpeg)

one is the app store the other is the photos app.

**Comment by ianhandsup** [comment]
This happens on and off, it might be hard to recreate.

**Comment by jacobcxdev** [comment]
This is a known issue, and appears to happen every time you reopen Messages.

I won’t fix this (for now), as I have absolutely no idea what’s causing it, and I’m tired of reverse engineering ChatKit.

Iris is open to pull requests if anyone decides to give it a go.

**Comment by ianhandsup** [comment]
> This is a known issue, and appears to happen every time you reopen Messages.
> 
> I won’t fix this (for now), as I have absolutely no idea what’s causing it, and I’m tired of reverse engineering ChatKit.
> 
> Iris is open to pull requests if anyone decides to give it a go.

I see, thank you!
